version: "3.8"

services:
  api:
    container_name: itunes_api
    build: ./api
    command: npm start
    stdin_open: true
    volumes:
      - ./api:/usr/src/
      - /usr/src/node_modules
    environment:
      - PORT=3001
    ports:
      - 3001:3001

  front:
    container_name: itunes_front
    build: ./front
    command: npm run dev
    stdin_open: true
    volumes:
      - ./front:/usr/src/
      - /usr/src/node_modules
    ports:
      - 3000:3000
    depends_on:
      - api
